# Copyright IBM Corp. 2026

policytest {
  targets = ["wafv2-webacl-should-have-logging-enabled.policy.hcl"]
}

# PASS: web ACL referenced by a logging configuration
resource "aws_wafv2_web_acl" "pass_logged" {
  attrs = {
    name  = "logged"
    scope = "REGIONAL"
    arn   = "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/logged/11111111"
  }
}

# Lookup-only companion for pass_logged
resource "aws_wafv2_web_acl_logging_configuration" "logging_for_logged" {
  skip = true
  attrs = {
    resource_arn            = "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/logged/11111111"
    log_destination_configs = ["arn:aws:logs:us-east-1:123456789012:log-group:aws-waf-logs-logged"]
  }
}

# Lookup-only companion pointing at a web ACL that is not in this file
resource "aws_wafv2_web_acl_logging_configuration" "logging_for_other" {
  skip = true
  attrs = {
    resource_arn            = "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/other/22222222"
    log_destination_configs = ["arn:aws:logs:us-east-1:123456789012:log-group:aws-waf-logs-other"]
  }
}

# FAIL: logging configuration references a different web ACL (also covers the no-config case)
resource "aws_wafv2_web_acl" "fail_not_logged" {
  expect_failure = true
  attrs = {
    name  = "not-logged"
    scope = "REGIONAL"
    arn   = "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/not-logged/33333333"
  }
}

# FAIL: CLOUDFRONT-scoped web ACL with no logging configuration
resource "aws_wafv2_web_acl" "fail_cloudfront_not_logged" {
  expect_failure = true
  attrs = {
    name  = "cf-not-logged"
    scope = "CLOUDFRONT"
    arn   = "arn:aws:wafv2:us-east-1:123456789012:global/webacl/cf-not-logged/44444444"
  }
}

# FAIL: arn omitted (missing attribute) and no logging configuration
resource "aws_wafv2_web_acl" "fail_missing_arn" {
  expect_failure = true
  attrs = {
    name  = "no-arn"
    scope = "REGIONAL"
  }
}

# Generated by Terraform Policy Agent 0.0.32
# Generated at: 2026-10-07 06:44:38 UTC
# Source: ./data/input1-pci/sentinels/wafv2-webacl-should-have-logging-enabled.sentinel
# LLM: github-copilot / claude-sonnet-5.5
